'use client';
import { useEffect,useMemo,useState } from 'react';
import { CalendarDays,Clock3,Inbox,MapPin,Menu,Navigation,Plane,Plus,Search,Sparkles,Trash2,X } from 'lucide-react';
import RegisterSW from './register-sw';
import type { AppData,InboxItem,Schedule,Trip } from '@/lib/types';
const uid=()=>crypto.randomUUID(); const toMin=(t:string)=>{const[h,m]=t.split(':').map(Number);return h*60+m}; const toTime=(n:number)=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`; const dur=(n:number)=>`${Math.floor(n/60)?Math.floor(n/60)+'시간 ':''}${n%60?n%60+'분':''}`.trim();
const seedTrip:Trip={id:'trip-demo',title:'삿포로 여름휴가',startDate:'2026-08-14',endDate:'2026-08-17',city:'삿포로',dayStart:'09:00',dayEnd:'21:00',travelMode:'TRANSIT'};
const seed:AppData={activeTripId:seedTrip.id,trips:[seedTrip],schedules:[
{id:'s1',tripId:seedTrip.id,title:'호텔 출발',date:'2026-08-15',start:'09:00',duration:20,type:'manual',address:'삿포로역 인근'},
{id:'s2',tripId:seedTrip.id,title:'니조시장',date:'2026-08-15',start:'09:35',duration:80,type:'place',address:'삿포로시 주오구',location:{lat:43.0603,lng:141.3565},openingHours:['07:00–17:00']},
{id:'s3',tripId:seedTrip.id,title:'삿포로 맥주박물관',date:'2026-08-15',start:'13:30',duration:90,type:'place',address:'삿포로시 히가시구',location:{lat:43.0716,lng:141.3684},openingHours:['11:00–18:00']}
],inbox:[{id:'i1',tripId:seedTrip.id,title:'스프카레 가라쿠',duration:80,type:'place',priority:3,address:'삿포로시 주오구'},{id:'i2',tripId:seedTrip.id,title:'다누키코지 쇼핑',duration:90,type:'place',priority:2,address:'다누키코지 상점가'}]};
function dates(a:string,b:string){const out=[];for(let d=new Date(a+'T00:00:00');d<=new Date(b+'T00:00:00');d.setDate(d.getDate()+1))out.push(d.toISOString().slice(0,10));return out}
export default function Home(){
 const[data,setData]=useState<AppData>(seed),[loaded,setLoaded]=useState(false),[tab,setTab]=useState<'schedule'|'map'|'inbox'|'settings'>('schedule'),[modal,setModal]=useState<string|null>(null),[date,setDate]=useState('2026-08-15'),[gap,setGap]=useState<{start:string;end:string}|null>(null);
 useEffect(()=>{try{const r=localStorage.getItem('tripflow-v2');if(r)setData(JSON.parse(r))}catch{}setLoaded(true)},[]); useEffect(()=>{if(loaded)localStorage.setItem('tripflow-v2',JSON.stringify(data))},[data,loaded]);
 const trip=data.trips.find(t=>t.id===data.activeTripId)||data.trips[0]; const allDates=dates(trip.startDate,trip.endDate); useEffect(()=>{if(!allDates.includes(date))setDate(trip.startDate)},[trip.id]);
 const day=useMemo(()=>data.schedules.filter(s=>s.tripId===trip.id&&s.date===date).sort((a,b)=>toMin(a.start)-toMin(b.start)),[data,date,trip.id]);
 const start=toMin(trip.dayStart),end=toMin(trip.dayEnd); const gaps=useMemo(()=>{let cur=start;const o:{start:string;end:string;minutes:number}[]=[];day.forEach(s=>{const st=toMin(s.start);if(st>cur)o.push({start:toTime(cur),end:s.start,minutes:st-cur});cur=Math.max(cur,st+s.duration)});if(cur<end)o.push({start:toTime(cur),end:toTime(end),minutes:end-cur});return o.filter(x=>x.minutes>=30)},[day,start,end]); const used=day.reduce((a,s)=>a+s.duration,0); const ib=data.inbox.filter(i=>i.tripId===trip.id);
 const patch=(p:Partial<AppData>)=>setData(v=>({...v,...p})); const del=(id:string)=>patch({schedules:data.schedules.filter(s=>s.id!==id)});
 const addToGap=(i:InboxItem)=>{if(!gap)return;patch({schedules:[...data.schedules,{...i,date,start:gap.start}],inbox:data.inbox.filter(x=>x.id!==i.id)});setModal(null)};
 return <main><RegisterSW/><header><button className="plain" onClick={()=>setModal('trips')}><Menu/></button><div><span className="eyebrow">TRIPFLOW</span><h1>{trip.title}</h1><p>{trip.startDate.replaceAll('-','.')} ― {trip.endDate.replaceAll('-','.')} · {trip.city}</p></div><button className="round" onClick={()=>setModal('add')}><Plus/></button></header>
 <section className="date-strip">{allDates.map(d=><button key={d} className={d===date?'active':''} onClick={()=>setDate(d)}><small>{Number(d.slice(5,7))}/{Number(d.slice(8))}</small><b>{['일','월','화','수','목','금','토'][new Date(d+'T00:00:00').getDay()]}</b></button>)}</section>
 {tab==='schedule'&&<><section className="summary"><div><Clock3/><span>일정</span><b>{dur(used)}</b></div><div><Sparkles/><span>남은 시간</span><b>{dur(Math.max(0,end-start-used))}</b></div></section><section className="timeline">{day.length===0&&<p className="empty">아직 일정이 없어요. + 버튼으로 추가해보세요.</p>}{day.map((s,i)=><div className="timeline-row" key={s.id}><div className="time"><b>{s.start}</b><span>{toTime(toMin(s.start)+s.duration)}</span></div><div className={'dot '+s.type}/><article><div className="card-head"><div><span className="type">{s.type==='flight'?'항공편':s.type==='place'?'장소':'일정'}</span><h3>{s.title}</h3></div><button className="icon" onClick={()=>del(s.id)}><Trash2 size={16}/></button></div>{s.address&&<p><MapPin size={14}/>{s.address}</p>}<p><Clock3 size={14}/>{dur(s.duration)}</p>{s.openingHours?.[0]&&<small>{s.openingHours[0]}</small>}</article>{i<day.length-1&&<div className="transfer"><Navigation size={13}/>{day[i+1].transferMinutes||20}분 예상 이동</div>}</div>)}{gaps.map(g=><button className="gap" key={g.start} onClick={()=>{setGap(g);setModal('gap')}}><Plus size={16}/>{g.start}–{g.end} · {dur(g.minutes)} 비어 있음</button>)}</section></>}
 {tab==='map'&&<section className="panel"><h2>오늘의 동선</h2><p className="muted">장소를 누르면 구글 지도에서 열 수 있어요.</p>{day.map((s,i)=><a className="map-stop" key={s.id} href={s.mapUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address||s.title)}`} target="_blank"><b>{i+1}</b><span>{s.title}</span><small>{s.start}</small></a>)}</section>}
 {tab==='inbox'&&<section className="panel"><div className="section-title"><div><h2>Inbox</h2><p>날짜가 아직 정해지지 않은 후보</p></div><button className="round small" onClick={()=>setModal('add')}><Plus/></button></div>{ib.map(i=><article className="inbox-card" key={i.id}><div><h3>{i.title}</h3><p>{i.address||'장소 미정'} · {dur(i.duration)}</p></div><span>{'★'.repeat(i.priority)}</span></article>)}</section>}
 {tab==='settings'&&<Settings trip={trip} save={t=>patch({trips:data.trips.map(x=>x.id===t.id?t:x)})}/>}<nav>{[['schedule',CalendarDays,'일정'],['map',MapPin,'지도'],['inbox',Inbox,'Inbox'],['settings',Menu,'설정']].map(([k,I,l]:any)=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I/><span>{l}</span></button>)}</nav>
 {modal&&<Modal close={()=>setModal(null)}>{modal==='add'&&<AddMenu choose={setModal}/>} {modal==='manual'&&<Manual trip={trip} date={date} add={(x,toInbox)=>{toInbox?patch({inbox:[...data.inbox,x as InboxItem]}):patch({schedules:[...data.schedules,x as Schedule]});setModal(null)}}/>} {modal==='place'&&<Place trip={trip} date={date} add={(x,toInbox)=>{toInbox?patch({inbox:[...data.inbox,x as InboxItem]}):patch({schedules:[...data.schedules,x as Schedule]});setModal(null)}}/>} {modal==='flight'&&<Flight trip={trip} add={xs=>{patch({schedules:[...data.schedules,...xs]});setModal(null)}}/>} {modal==='gap'&&gap&&<Gap gap={gap} items={ib} add={addToGap}/>} {modal==='trips'&&<Trips data={data} save={setData} close={()=>setModal(null)}/>}</Modal>}</main>
}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><div className="modal"><button className="close" onClick={close}><X/></button>{children}</div></div>}
function AddMenu({choose}:{choose:(s:string)=>void}){return <><h2>일정 추가</h2><p className="sub">가장 편한 방법을 골라주세요.</p><div className="menu"><button onClick={()=>choose('flight')}><Plane/><span><b>항공편 조회</b><small>편명과 날짜로 자동 추가</small></span></button><button onClick={()=>choose('place')}><Search/><span><b>장소 검색</b><small>주소·영업시간 불러오기</small></span></button><button onClick={()=>choose('manual')}><Plus/><span><b>직접 입력</b><small>휴식·쇼핑·예약 일정</small></span></button></div></>}
function Manual({trip,date,add}:{trip:Trip;date:string;add:(x:any,b:boolean)=>void}){const[title,setTitle]=useState(''),[start,setStart]=useState('12:00'),[duration,setDuration]=useState(60),[address,setAddress]=useState('');const base={id:uid(),tripId:trip.id,title:title||'새 일정',duration,type:'manual' as const,address};return <><h2>직접 입력</h2><label>일정명<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 호텔에서 쉬기"/></label><label>장소 또는 메모<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>시작 시간<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>이용 시간(분)<input type="number" value={duration} onChange={e=>setDuration(+e.target.value)}/></label><div className="two"><button className="primary" onClick={()=>add({...base,date,start},false)}>일정에 추가</button><button className="ghost" onClick={()=>add({...base,priority:1},true)}>Inbox</button></div></>}
function Place({trip,date,add}:{trip:Trip;date:string;add:(x:any,b:boolean)=>void}){const[q,setQ]=useState(''),[list,setList]=useState<any[]>([]),[loading,setLoading]=useState(false),[start,setStart]=useState('12:00'),[duration,setDuration]=useState(60);const search=async()=>{setLoading(true);try{const r=await fetch('/api/places/search?q='+encodeURIComponent(q));const d=await r.json();setList(d.places||[])}finally{setLoading(false)}};return <><h2>장소 검색</h2><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="장소명" onKeyDown={e=>e.key==='Enter'&&search()}/><button onClick={search}>{loading?'…':'검색'}</button></div><div className="two"><label>시작<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>체류(분)<input type="number" value={duration} onChange={e=>setDuration(+e.target.value)}/></label></div>{list.map(p=>{const base={id:uid(),tripId:trip.id,title:p.displayName?.text||q,duration,type:'place' as const,address:p.formattedAddress,location:p.location?{lat:p.location.latitude,lng:p.location.longitude}:undefined,openingHours:p.regularOpeningHours?.weekdayDescriptions,mapUrl:p.googleMapsUri};return <article className="result" key={p.id}><h3>{base.title}</h3><p>{base.address}</p><small>{base.openingHours?.[0]}</small><div className="two"><button className="primary" onClick={()=>add({...base,date,start},false)}>일정 추가</button><button className="ghost" onClick={()=>add({...base,priority:2},true)}>Inbox</button></div></article>})}</>}
function Flight({trip,add}:{trip:Trip;add:(x:Schedule[])=>void}){const[code,setCode]=useState('KE765'),[date,setDate]=useState(trip.startDate),[loading,setLoading]=useState(false);const go=async()=>{setLoading(true);try{const r=await fetch(`/api/flights?flight=${code}&date=${date}`),d=await r.json(),x=d.flight;if(!x)throw 0;add([{id:uid(),tripId:trip.id,title:`${code} ${x.departure.airport} 출발`,date,start:(x.departure.scheduled||'07:30').slice(11,16),duration:30,type:'flight',address:x.departure.iata,note:`터미널 ${x.departure.terminal||'-'}`,fixed:true},{id:uid(),tripId:trip.id,title:`${x.arrival.airport} 도착`,date,start:(x.arrival.scheduled||'10:10').slice(11,16),duration:30,type:'flight',address:x.arrival.iata,note:`터미널 ${x.arrival.terminal||'-'}`,fixed:true}])}catch{alert('조회 결과가 없어요. API 키와 편명·날짜를 확인해주세요.')}finally{setLoading(false)}};return <><h2>항공편 조회</h2><label>편명<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>탑승일<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary full" onClick={go}>{loading?'조회 중…':'조회해서 일정에 추가'}</button></>}
function Gap({gap,items,add}:{gap:{start:string;end:string};items:InboxItem[];add:(i:InboxItem)=>void}){const n=toMin(gap.end)-toMin(gap.start),ok=items.filter(i=>i.duration+20<=n);return <><h2>{gap.start}–{gap.end}</h2><p className="sub">예상 이동 20분까지 포함해 들어가는 후보예요.</p>{ok.map(i=><article className="result" key={i.id}><h3>{i.title}</h3><p>체류 {dur(i.duration)} · 총 {dur(i.duration+20)}</p><button className="primary full" onClick={()=>add(i)}>이 시간에 넣기</button></article>)}{!ok.length&&<p className="empty">들어갈 수 있는 Inbox 일정이 없어요.</p>}</>}
function Settings({trip,save}:{trip:Trip;save:(t:Trip)=>void}){return <section className="panel"><h2>여행 설정</h2><label>여행 이름<input value={trip.title} onChange={e=>save({...trip,title:e.target.value})}/></label><label>도시<input value={trip.city} onChange={e=>save({...trip,city:e.target.value})}/></label><div className="two"><label>하루 시작<input type="time" value={trip.dayStart} onChange={e=>save({...trip,dayStart:e.target.value})}/></label><label>하루 종료<input type="time" value={trip.dayEnd} onChange={e=>save({...trip,dayEnd:e.target.value})}/></label></div><div className="notice"><b>현재 저장 방식</b><p>이 기기의 Safari에 자동 저장됩니다. README의 Supabase 설정을 적용하면 클라우드 동기화로 확장할 수 있어요.</p></div><div className="notice"><b>아이폰 설치</b><p>Safari 공유 버튼 → 홈 화면에 추가를 누르세요.</p></div></section>}
function Trips({data,save,close}:{data:AppData;save:(d:AppData)=>void;close:()=>void}){const[t,setT]=useState('새 여행'),[city,setCity]=useState(''),[s,setS]=useState(new Date().toISOString().slice(0,10)),[e,setE]=useState(new Date().toISOString().slice(0,10));return <><h2>내 여행</h2>{data.trips.map(x=><button className={'trip-choice '+(x.id===data.activeTripId?'active':'')} key={x.id} onClick={()=>{save({...data,activeTripId:x.id});close()}}><b>{x.title}</b><small>{x.startDate} ― {x.endDate}</small></button>)}<hr/><h3>새 여행 만들기</h3><label>이름<input value={t} onChange={x=>setT(x.target.value)}/></label><label>도시<input value={city} onChange={x=>setCity(x.target.value)}/></label><div className="two"><label>시작<input type="date" value={s} onChange={x=>setS(x.target.value)}/></label><label>종료<input type="date" value={e} onChange={x=>setE(x.target.value)}/></label></div><button className="primary full" onClick={()=>{const n:Trip={id:uid(),title:t,startDate:s,endDate:e,city,dayStart:'09:00',dayEnd:'21:00',travelMode:'TRANSIT'};save({...data,trips:[...data.trips,n],activeTripId:n.id});close()}}>만들기</button></>}
